# toolchains/BUCK
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
    cxx_flags = ["-std=c++20"],
)

system_python_toolchain(
    name='python',
    visibility=["PUBLIC"],
    interpreter = './venv/bin/python3'
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)
