name: QUICK BUCK2 BUILD AND TEST
on: [push, pull_request, workflow_dispatch]

env:
  CPP_TIMEOUT_SEC: 5
  PY_TIMEOUT_SEC: 5

jobs:
  build:
    name: Ubuntu Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: 'true'
      - run: sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
      - name: install buck2
        uses: dtolnay/install-buck2@v1 
      - run: buck2 clean
      - run: |
            buck2 build //:py_install_venv
            source venv/bin/activate
            buck2 build //...
            deactivate
            buck2 build //:py_uninstall_venv
